CREATE TABLE PRODUCERS
(
    PRODUCER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NAME  NVARCHAR(250) NOT NULL,
    LAST_NAME   NVARCHAR(250) NOT NULL,
    BIRTHDAY    DATE          NOT NULL,
    EMAIL       NVARCHAR(250) NOT NULL,
    IS_MALE     BOOLEAN       NOT NULL
);

CREATE TABLE MOVIES
(
    MOVIE_ID      INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCER_ID   INT REFERENCES PRODUCERS,
    TITLE         NVARCHAR(250) NOT NULL,
    RELEASE_DATE  DATE          NOT NULL,
    MOVIE_RATING  FLOAT         NOT NULL,
    IS_TOP_RANKED BOOLEAN       NOT NULL,
    GENRE         INT           NOT NULL
);
